### ISSUE TITLE
global cli broken if there is any babel version mismatch

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#157]
If there is any difference in the babel-version installed globally, vs that installed locally, you get:

```js
TypeError: Plugin "babel-plugin-espower" is resolving to a different Babel version than what is performing the transformation.
 ```
We could use [`fallback-cli`](https://www.npmjs.com/package/fallback-cli) to always use the local install of ava if there is one. Things might get weird if they had no local install, but did have `babel-runtime` installed locally. I'd need to play with it.

@sindresorhus I'm happy to tackle this, but I know [you have reservations](https://github.com/sindresorhus/xo/pull/32#issuecomment-144939822) with the idea.

**Comment by uiureo** [comment]
The `babel-plugin-espower` issue is fixed in #129. Is it different?
Is there still the problem at master?

**Comment by jamestalmage** [comment]
Yes. Still a problem (when executing `ava` directly from console - `npm test` works fine). Also fixed when I upgraded ava to match.

**Comment by sindresorhus** [comment]
@jamestalmage I'm warming up to the idea, but would like to hear some more peoples thought about it in   https://github.com/sindresorhus/xo/pull/32.

**Comment by sindresorhus** [comment]
No matter which direction we go, I think it's important we find a way to get rid of the mismatch problems once and for all.
